cache:
  paths:
  - /root/.cache

stages:
  - test
  
before_script:
  - pip install --disable-pip-version-check --upgrade pip
  - pip install -r requirements.txt

py35:
  stage: test
  image: python:3.5
  artifacts:
    paths:
      - coverage.xml
  script:
    - python -m pytest --cov=sensormesh --cov-report term --cov-report xml

py36:
  stage: test
  image: python:3.6
  artifacts:
    paths:
      - coverage.xml
  script:
    - python -m pytest --cov=sensormesh --cov-report term --cov-report xml
