sudo: false

language: python

python:
  - 3.6
  - 3.5

install:
  - pip install --disable-pip-version-check --upgrade pip
  - pip install --upgrade wheel setuptools
  - pip install -r requirements.txt

script:
  - python -m pytest --junitxml=result.xml --cov=sensormesh --cov-report term --cov-report xml

after_success:
  - if [[ -n $COVERALLS_REPO_TOKEN ]]; then pip install python-coveralls && coveralls; fi
  - if [[ -n $CODACY_PROJECT_TOKEN ]]; then pip install codacy-coverage && python-codacy-coverage -r coverage.xml; fi
  - if [[ -n $CODECOV_TOKEN ]]; then pip install codecov && codecov; fi
  - if ($SHIPPABLE); then mkdir -p shippable/testresults && cp result.xml shippable/testresults; fi
  - if ($SHIPPABLE); then mkdir -p shippable/codecoverage && cp coverage.xml shippable/codecoverage; fi
 