sudo: false

language: python

python:
  - 3.5
  - 3.4
  - nightly

matrix:
  allow_failures:
    - python: nightly

install:
  - pip install --disable-pip-version-check --upgrade pip
  - pip install -r requirements.txt

script:
  - python -m pytest --cov=sensormesh --cov-report term --cov-report xml

after_success:
  - pip install python-coveralls
  - coveralls

  - pip install codacy-coverage
  - python-codacy-coverage -r coverage.xml

  - pip install codecov
  - codecov
